"""
Scira Retrieval Agent

Implements literature retrieval workflow:
- Search strategy generation
- MCP paper search integration (via HTTP API)
- Human-in-the-loop approval
"""

import os
import json
import requests
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from datetime import datetime, timedelta

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.prompts import ChatPromptTemplate

from config.settings import get_config, SciraConfig
from src.utils.logger import logger
from src.agents.prompts import (
    RETRIEVAL_TRANSLATE_PROMPT,
    RETRIEVAL_ANALYZE_PROMPT,
    RETRIEVAL_APPROVAL_PROMPT,
    RETRIEVAL_SYSTEM,
)

# MCP Server 配置
MCP_SERVER_HOST = os.getenv("MCP_SERVER_HOST", "localhost")
MCP_SERVER_PORT = int(os.getenv("MCP_SERVER_PORT", "8001"))
MCP_API_BASE = f"http://{MCP_SERVER_HOST}:{MCP_SERVER_PORT}/api/paper-search"


@dataclass
class SearchStrategy:
    """Search strategy generated by the agent."""
    keywords: List[str]
    boolean_query: str
    categories: List[str]
    date_range: Tuple[str, str]
    max_results: int
    rationale: str


@dataclass
class RetrievalResult:
    """Retrieval operation result."""
    papers: List[Dict[str, Any]]  # 论文列表，从MCP API返回
    search_strategy: SearchStrategy
    selected_paper_ids: List[str]
    errors: List[str] = field(default_factory=list)


class RetrievalAgent:
    """
    Retrieval Agent for literature search.

    Responsibilities:
    1. Analyze user query and generate search strategy
    2. Execute paper search via MCP HTTP API
    3. Manage human approval checkpoints
    4. Select relevant papers for reading
    """

    def __init__(self, config: Optional[SciraConfig] = None):
        """Initialize Retrieval Agent."""
        self.config = config or get_config()
        self.mcp_api_base = MCP_API_BASE
        # 尝试从MCP获取搜索策略生成器
        try:
            from src.tools.arxiv_api import SearchStrategyGenerator
            self.strategy_generator = SearchStrategyGenerator()
        except ImportError:
            self.strategy_generator = None

    def analyze_query(self, user_query: str) -> Dict[str, Any]:
        """
        Analyze user query and expand research topic.

        Args:
            user_query: Raw user query

        Returns:
            Analysis results with expanded topic
        """
        from config.settings import get_llm_client

        # Check if query is in Chinese, translate to English if needed
        is_chinese = any('一' <= char <= '鿿' for char in user_query)
        query_to_analyze = user_query

        if is_chinese:
            # Translate Chinese to English for better paper search
            translate_prompt = RETRIEVAL_TRANSLATE_PROMPT.format(query=user_query)

            llm = get_llm_client(self.config)
            translate_messages = [
                SystemMessage(content=RETRIEVAL_SYSTEM),
                HumanMessage(content=translate_prompt)
            ]
            translate_response = llm.invoke(translate_messages)
            query_to_analyze = translate_response.content.strip()
            query_to_analyze = query_to_analyze.strip('"').strip("'")

        # Use LLM to expand and normalize the query
        prompt = RETRIEVAL_ANALYZE_PROMPT.format(query=query_to_analyze)

        llm = get_llm_client(self.config)

        messages = [
            SystemMessage(content=RETRIEVAL_SYSTEM),
            HumanMessage(content=prompt)
        ]

        response = llm.invoke(messages)
        result = self._parse_json_response(response.content)

        # Store original query for reference
        if is_chinese:
            result["original_query"] = user_query
            result["translated_query"] = query_to_analyze

        return result

    def generate_search_strategy(
        self,
        topic: str,
        key_concepts: List[str],
    ) -> SearchStrategy:
        """
        Generate search strategy from topic analysis.

        Args:
            topic: Normalized research topic
            key_concepts: Key concepts from query analysis

        Returns:
            SearchStrategy object
        """
        # Generate keywords - use strategy_generator or fallback to key_concepts
        if self.strategy_generator is not None:
            keywords = self.strategy_generator.generate_keywords(topic)
            categories = self.strategy_generator.suggest_categories(topic)
        else:
            # Fallback: use key_concepts as keywords
            logger.warning("strategy_generator is None, using key_concepts as fallback")
            keywords = key_concepts.copy() if key_concepts else [topic]
            categories = []

        keywords.extend(key_concepts[:3])
        keywords = list(set(keywords))[:10]  # Deduplicate, limit to 10

        # Build boolean query
        boolean_query = " OR ".join([f'"{k}"' for k in keywords[:5]])
        boolean_query = f"({boolean_query})"

        # Date range: last 2 years
        end_date = datetime.now()
        start_date = end_date - timedelta(days=730)  # 2 years

        return SearchStrategy(
            keywords=keywords,
            boolean_query=boolean_query,
            categories=categories,
            date_range=(start_date.strftime("%Y-%m-%d"), end_date.strftime("%Y-%m-%d")),
            max_results=self.config.max_literature_count,
            rationale=f"Search for {topic} with focus on recent papers (last 2 years)",
        )

    def execute_search(self, strategy: SearchStrategy) -> List[Dict[str, Any]]:
        """
        Execute search using MCP HTTP API.

        Args:
            strategy: Search strategy

        Returns:
            List of paper dicts from MCP API
        """
        logger.info(f"Executing search via MCP API with keywords: {strategy.keywords}")
        logger.info(f"Boolean query: {strategy.boolean_query}")
        logger.info(f"Max results: {strategy.max_results}")

        try:
            # 调用MCP API搜索论文
            response = requests.post(
                f"{self.mcp_api_base}/search",
                json={
                    "query": strategy.boolean_query,
                    "max_results": strategy.max_results,
                    "sources": "all",
                },
                timeout=60
            )
            response.raise_for_status()
            result = response.json()

            papers = result.get("papers", [])
            logger.info(f"Search completed, found {len(papers)} papers")
            return papers

        except requests.exceptions.RequestException as e:
            logger.error(f"MCP API call failed: {e}")
            # 返回空列表作为后备
            return []

    def select_papers(
        self,
        papers: List[Dict[str, Any]],
        max_select: int = 10,
    ) -> List[str]:
        """
        Select most relevant papers from search results.

        Uses simple relevance heuristic based on:
        - Recency (newer papers preferred)
        - Citation count (if available in comments)

        Args:
            papers: List of papers
            max_select: Maximum papers to select

        Returns:
            List of selected paper IDs
        """
        # Sort by published date (newer first)
        def get_published_date(p):
            date_str = p.get("published", p.get("published_date", ""))
            if date_str:
                try:
                    return datetime.fromisoformat(date_str.replace("Z", "+00:00"))
                except:
                    pass
            return datetime.min

        sorted_papers = sorted(
            papers,
            key=get_published_date,
            reverse=True
        )

        # Select top N
        selected = sorted_papers[:max_select]
        return [p.get("paper_id", p.get("id", "")) for p in selected]

    def generate_retrieval_approval_prompt(
        self,
        strategy: SearchStrategy,
        papers: List[Dict[str, Any]],
    ) -> str:
        """
        Generate human approval prompt for retrieval stage.

        Args:
            strategy: Search strategy
            papers: Found papers

        Returns:
            Formatted approval prompt
        """
        paper_list = "\n".join([
            f"- **{p.get('title', 'Untitled')}** ({p.get('paper_id', p.get('id', 'N/A'))})\n  Authors: {', '.join(p.get('authors', [])[:3])}\n  Date: {p.get('published', p.get('published_date', 'N/A'))}"
            for p in papers[:10]
        ])

        return f"""## 📋 检索条件审核

### 搜索策略
- **关键词**: {', '.join(strategy.keywords)}
- **分类**: {', '.join(strategy.categories)}
- **日期范围**: {strategy.date_range[0]} ~ {strategy.date_range[1]}
- **最大结果数**: {strategy.max_results}
- **理由**: {strategy.rationale}

### 检索到 {len(papers)} 篇论文，显示前 10 篇:

{paper_list}

---

**请确认是否满意检索结果，或提出修改建议。**

回复说明：
- 直接输入 "确认" 或 "approve" 继续
- 输入修改建议（如 "添加更多关于 XXX 的论文"）
- 输入数字选择特定论文（如 "选择 1,3,5,7"）
"""

    def run(
        self,
        user_query: str,
        auto_approve: bool = False,
        approved_topic: Optional[str] = None,
        approved_keywords: Optional[List[str]] = None,
    ) -> RetrievalResult:
        """
        Run complete retrieval workflow.

        Args:
            user_query: User research query
            auto_approve: Skip human approval if True
            approved_topic: 用户已确认的规范化主题（来自检索审批）。
                            提供时跳过 analyze_query，直接用该主题检索，
                            避免对中文查询二次翻译得到空主题。
            approved_keywords: 用户已确认的关键词，提供时直接用于策略生成。

        Returns:
            RetrievalResult with papers and metadata
        """
        errors = []

        # Step 1: Analyze query（若已有审批通过的 topic/keywords 则跳过，直接复用）
        if approved_topic:
            topic = approved_topic.strip()
            key_concepts = approved_keywords or []
            logger.info(f"=== Step 1: Using APPROVED conditions (skip analyze) | topic='{topic}', concepts={key_concepts} ===")
        else:
            logger.info("=== Step 1: Analyzing query ===")
            try:
                analysis = self.analyze_query(user_query)
                topic = analysis.get("normalized_topic", user_query)
                key_concepts = analysis.get("key_concepts", [])

                # If translation happened, use translated query
                if "translated_query" in analysis:
                    topic = analysis.get("translated_query", topic)

                # Fallback: if topic is still Chinese, use simple translation
                if any('一' <= char <= '鿿' for char in topic):
                    topic = self._simple_translate(user_query)

                logger.info(f"Query analysis complete: topic='{topic}', key_concepts={key_concepts}")
            except Exception as e:
                errors.append(f"Query analysis failed: {e}")
                # Fallback translation
                topic = self._simple_translate(user_query)
                key_concepts = []
                logger.warning(f"Query analysis failed, using fallback: {e}")

        # 兜底：topic 为空（如翻译失败）时回退到 user_query，避免用空串检索
        if not topic:
            topic = user_query or "research"
            logger.warning(f"topic empty after analysis, fallback to: {topic}")

        # Step 2: Generate search strategy
        logger.info("=== Step 2: Generating search strategy ===")
        strategy = self.generate_search_strategy(topic, key_concepts)
        logger.info(f"Search strategy generated: {len(strategy.keywords)} keywords")

        # Step 3: Execute search
        logger.info("=== Step 3: Executing arXiv search ===")
        try:
            papers = self.execute_search(strategy)
            logger.info(f"Search execution complete: {len(papers)} papers found")
        except Exception as e:
            errors.append(f"Search execution failed: {e}")
            papers = []
            logger.error(f"Search failed: {e}")

        # Step 4: Select papers
        logger.info("=== Step 4: Selecting papers ===")
        selected_ids = self.select_papers(papers)
        logger.info(f"Selected {len(selected_ids)} papers for reading")

        # Step 5: Human approval (placeholder - integration with workflow)

        return RetrievalResult(
            papers=papers,
            search_strategy=strategy,
            selected_paper_ids=selected_ids,
            errors=errors,
        )

    def _simple_translate(self, query: str) -> str:
        """Simple fallback translation for common Chinese research terms."""
        translations = {
            "强化学习": "reinforcement learning",
            "Agent": "agent",
            "智能体": "intelligent agent",
            "应用": "application",
            "最新": "latest",
            "动向": "trend",
            "深度学习": "deep learning",
            "机器学习": "machine learning",
            "人工智能": "artificial intelligence",
            "神经网络": "neural network",
            "大语言模型": "large language model",
            "LLM": "large language model",
            "扩散模型": "diffusion model",
            "计算机视觉": "computer vision",
            "自然语言处理": "natural language processing",
        }
        result = query
        for cn, en in translations.items():
            result = result.replace(cn, en)
        return result

    def _parse_json_response(self, response: str) -> Dict[str, Any]:
        """Parse JSON from LLM response."""
        import re

        # Try to extract JSON
        match = re.search(r'\{[\s\S]*\}', response)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                pass

        # Fallback: return raw response
        return {"raw_response": response}


# Convenience function
def retrieve_papers(
    query: str,
    max_results: int = 10,
) -> RetrievalResult:
    """
    Quick retrieval function.

    Args:
        query: Research query
        max_results: Max papers to retrieve

    Returns:
        RetrievalResult
    """
    from config.settings import get_config

    config = get_config()
    config.max_literature_count = max_results

    agent = RetrievalAgent(config)
    return agent.run(query)
